### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dtrue** [metaskills/less-rails-bootstrap-test#1]
I'm sure there is no issue but I'm struggling with following your full index example.  I've updated my project based on everything in your test example (including the precompile piece).  Question though, should your full control file be added manually or is this something that should be generated?  I'm a noob so I apologize if I've missed the obvious.

I also get a dns error trying to click this link under the Full Control and Customization section.
http://less-rails-bootstrap-test.dev/assets/full_control.css

Thanks so much in advance!
Dan

**Comment by metaskills** [comment]
Nothing is generated manually.

Also that URL assumes you were running something like http://pow.cx/ and I just most assumed familiarity with setting up localhost dev like that with Pow or the like. I just updated master to localhost:3000 style URLs to micic a vanilla `$ rails server`

**Comment by dtrue** [comment]
Do you have any thoughts on why the custom css files are not generated?  I
double checked the settings you documented but maybe I missed some implied
command to run somewhere to generate?

Thanks!
Dan

On Thu, Feb 23, 2012 at 5:00 AM, Ken Collins <
reply@reply.github.com

**Comment by metaskills** [comment]
Are your talking about running `rake assets:precompile`? I added those files to the list here.

https://github.com/metaskills/less-rails-bootstrap-test/blob/master/config/environments/production.rb#L46

Have you read this? It details everything.

http://guides.rubyonrails.org/asset_pipeline.html

**Comment by dtrue** [comment]
I really appreciate your help!  Last question :)

I think my question is before this step.  When I install the
less-rails-bootstrap I see that it creates files in my rvm/gems directory.
1. I don't see the file (full_controll.css) in any of the directories.
   How is this file generated?
2. Second - do I need to copy the assets directory in this rvm/gems
   directory _manually_ to my <project>/assets or <project>/vendor/assets
   folder?

Thanks so much!

I have a new idea...expert IM support for a fee.  I would pay you!

--Dan
On Thu, Feb 23, 2012 at 11:08 AM, Ken Collins <
reply@reply.github.com

**Comment by metaskills** [comment]
As I said before "Nothing is generated". It's hard to give you a good answer but in general you are way over thinking things and all over the place. Not trying to be offensive, just having a hard time here.

So question number two... absolutely not! If you had to do crap like that then the asset pipeline would be worth nothing. Basically my full_control.css file and the way I have organized the less files for that asset manifest is something I made in this project as an example of what a developer like "you" might choose to do. This is a working example of what may happen in your rails application to show to others how these tools are used.

**Comment by dtrue** [comment]
No offense taken - I'm sure I'm asking dumb questions.  I guess I'm having
a hard time trying to figure out how I should get/save the full_control.css
and your test directory structure in general.  Given that I don't see the
full_control file in the rvm/gem/...directory...I'm not sure how it gets
placed in my project directory.

If for some reason it's suppose to put this file in my project
directory...for whatever reason it's not under any of the assets
directories (app/public/lib/vendor).

Thanks,
Dan

Should this be present in a directory after I run rake bundle exec
assets:precompile or do I just copy the file from your fo

On Thu, Feb 23, 2012 at 12:09 PM, Ken Collins <
reply@reply.github.com

**Comment by metaskills** [comment]
Precompile is for deployment to the final server only. I'm not sure your getting what the asset pipeline is all about. Your not supposed to have anything in public/assets, etc. That's the point. The assets are dynamic and the source can come from gems, libs, etc. Only when they are precompiled (by your sysadmin on deploy or by Heroku post a deploy for you automatically) are the assets created and placed in public/assets. Otherwise, they are all dynamically compiled via sprockets via the engine it mounts in development mode at "/assets" of your app. 

Please, take a bit of time to learn about the asset pipeline in general. I highly advise that link i sent earlier or this http://railscasts.com/episodes/279-understanding-the-asset-pipeline
