### ISSUE TITLE
Using bootstrap variables in variables.less breaks precompile

### ISSUE THREAD

**Issue by nmrs** [metaskills/less-rails-bootstrap-test#2]
Using bootstrap variables in variables.less breaks rake assets:precompile

To test, change app/assets/stylesheets/full_control/variables.less to:

@linkColor: @grayDarker;

**Comment by metaskills** [comment]
Hmmm, that may be a less thing that avoids an issue in development. Easy workaround. Just make the `app/assets/stylesheets/full_control/variables.less` file do this below and it will work in dev/production/compile time.

``` css
@import "twitter/bootstrap/variables";
@linkColor: @grayDarker;
```

BTW, if you think you know why or how to fix this in less.js, less.rb or less-rails, please let me know.
